### ISSUE TITLE
[FEATURE REQUEST] is there a shutdown PSU on shutdown of pi option?

### ISSUE THREAD

**Issue by bolsoncerrado** [nils-org/OctoPrint-PSUControl-FHEM#1]
So the idea would be "send warning of printer's raspi being shutdown to FHEM, FHEM adds a delay, then launches a switch off to the smartswitch powering raspi/printer that reported the shutdown".

Makes any sense?

PS Crossposting issue#261@PSUControl Github
https://github.com/kantlivelong/OctoPrint-PSUControl/issues/261

**Comment by nils-a** [comment]
Closing, in favor of https://github.com/kantlivelong/OctoPrint-PSUControl/issues/261, as there is nothing this plugin can do, as long as OctoPrint-PSUControl does not "support" it.
